cloud:
  aws:
    s3:
      bucket: $BUCKET_NAME
      folder:
        articleImagesFolder: article-images/
        profileImagesFolder: profile-images/
    region:
      static: ap-northeast-2
    stack:
      auto: false